//
// Created by AlexHoring on 2023/5/25.
//

#ifndef FILESYSTEM_CONSTRAINTS_H
#define FILESYSTEM_CONSTRAINTS_H

//目录项的大小，128 bit = 16 Byte
#define DIRECTORY_ITEM_SIZE 128
//块大小，4096 Byte
#define BLOCK_SIZE 32768

//目录项总项数
#define DIRECTORY_NUMS (BLOCK_SIZE/DIRECTORY_ITEM_SIZE)

#endif //FILESYSTEM_CONSTRAINTS_H
